### ISSUE TITLE
Feature requests

### ISSUE THREAD

**Issue by r57zone** [peter10110/Android-SteamVR-controller#1]
1. Touch area for position tracking.
2. Button for up and down with gyroscope pitch and left and right with roll (click on button activate change position controller with gyroscope incline).
3. SteamVR driver without leapmotion (many do not have; it is very important, because some games and applications do not need position tracking, but would like to do it by 1 and 2 points).

Big buttons. maybe bug - https://i.imgur.com/PLsPw3f.png and does not exit the application using the back button.

Thanks.

**Comment by peter10110** [comment]
The buttons are big, because I realized something after I tried to use it in VR. You can't hit the smaller buttons. So I did a really ugly fix.

About feature requests: sorry, I abandoned the project.
